### ISSUE TITLE
Trouble installing PyCPD

### ISSUE THREAD

**Issue by ghost** [dpfau/pycpd#1]
Hi, I'm interested in using your algorithm for research purposes.
But... I'm having troubles with the installation : when I launch the setup.py, I recieve this message 

C:\Users\Bastien\Desktop\PBC\pycpd-master>python setup.py
missing cimport in module 'fast_gaussian_transform': cpd/fast_gaussian_transform.pyx
Compiling cpd/fast_gaussian_transform.pyx because it changed.
[1/1] Cythonizing cpd/fast_gaussian_transform.pyx
## Error compiling Cython file:

...
# distutils: language = c
## ^

cpd\fast_gaussian_transform.pyx:1:0: 'pycpd-master.cpd.fast_gaussian_transform'
is not a valid module name
Traceback (most recent call last):
  File "setup.py", line 13, in <module>
    ext_modules = cythonize(extensions)
  File "C:\Users\Bastien\Anaconda3\lib\site-packages\Cython\Build\Dependencies.py", line 877, in cythonize
    cythonize_one(*args)
  File "C:\Users\Bastien\Anaconda3\lib\site-packages\Cython\Build\Dependencies.py", line 997, in cythonize_one
    raise CompileError(None, pyx_file)
Cython.Compiler.Errors.CompileError: cpd/fast_gaussian_transform.pyx

Any idea why it is not working ?

Best,

Bastien

**Comment by dpfau** [comment]
Sorry Bastien, the library is no longer being developed. I only got about
halfway through porting it from MATLAB.
